name: Docker Image CI

on:
  push:
  pull_request:
  schedule:
    - cron: 0 6 * * 2

jobs:
  dockerRegistry:
    name: Docker Registry
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Docker Registry
      uses: actions/docker/login@c08a5fc9e0286844156fefff2c141072048141f6
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        
    - name: Build
      uses: actions/docker/cli@c08a5fc9e0286844156fefff2c141072048141f6
      with:
        args: build -t mpepping/jenkins:latest .
        
    - name: Push
      uses: actions/docker/cli@c08a5fc9e0286844156fefff2c141072048141f6
      with:
        args: push mpepping/jenkins:latest
